trigger:
- dev

resources:
- repo: self

pool:
  name: Laptop
  demands: agent.name -equals WinWsl

variables:
- group: 'Master.Project.Variable.Set'  # Add your key vault variable group

stages:
- stage: AppBuild
  displayName: 'Building LH Web App Code'
  jobs:
  - job: Build
    displayName: 'Build Application'
    steps:
    - task: UseNode@1
      inputs:
        versionSpec: '17.91'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)'
        artifactName: 'source'
      displayName: 'Publish Artifact'

- stage: DockerBuildandPush
  displayName: 'Build Docker Image and Push to ACR' 

  dependsOn: AppBuild
  jobs:
  - job: BuildAndPushDocker
    displayName: 'Build and Push Docker Image'
    steps:
    - download: current
      artifact: source
      displayName: 'Download Build Artifact'

    - task: Docker@2
      inputs:
        containerRegistry: 'POCAKS'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
      displayName: 'Build and Push Docker Image'




