trigger:
- dev

resources:
- repo: self

pool:
  name: Laptop
  demands: agent.name -equals WinWsl

variables:
- group: 'Master.Project.Variable.Set'  # Add your key vault variable group


stages:
- stage: AppBuild
  displayName: 'Building LH Web App Code'
  jobs:
  - job: Build
    condition: false
    displayName: 'Build Application'
    steps:
    - task: UseNode@1
      inputs:
        versionSpec: '17.91'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Install dependencies and build'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)'
        artifactName: 'source'
      displayName: 'Publish Artifact'

- stage: DockerBuildandPush
  displayName: 'Build Docker Image and Push to ACR' 

  dependsOn: AppBuild
  jobs:
  - job: BuildAndPushDocker
    condition: false
    displayName: 'Build and Push Docker Image'
    steps:
    - download: current
      artifact: source
      displayName: 'Download Build Artifact'

    - task: Docker@2
      inputs:
        containerRegistry: 'POCAKS'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
      displayName: 'Build and Push Docker Image'

- stage: CreatePullRequest
  jobs:
  - job: CreatePR
    condition: false
    variables:
        azureDevOpsOrganization: 'https://dev.azure.com/sunilchhabrams'
        projectName: 'master'
        repositoryName: 'NodeJsSampleRepo'
        sourceBranch: 'f1'
        targetBranch: 'qa'
    steps:
    - script: |
        echo "Installing Azure DevOps CLI extension"
        az extension add --name azure-devops
        echo "Creating Pull Request from $(sourceBranch) to $(targetBranch)"
        az devops configure --defaults organization=$(azureDevOpsOrganization) project=$(projectName)
        az repos pr create --repository $(repositoryName) \
            --source-branch $(sourceBranch) \
            --target-branch $(targetBranch) \
            --title "Merge $(sourceBranch) into $(targetBranch)" \
            --description "Auto PR created by Azure Pipelines" \
            --detect true
      displayName: 'Create Pull Request'
      env:
        AZURE_DEVOPS_EXT_PAT: $(PAT)

- stage: DeploytoAKSDev
  displayName: Deploy to AKS 
  jobs:
    - deployment: Dev
      environment: Dev
      strategy: 
       runOnce:
         deploy:
           steps:
            - task: KubernetesManifest@1
              inputs:
                action: 'deploy'
                connectionType: 'azureResourceManager'
                azureSubscriptionConnection: 'ADOAKSServiceConn'
                azureResourceGroup: 'poc'
                kubernetesCluster: 'demoaks68'
                namespace: 'Default'
                manifests: 'dep.yaml'

